name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Erick-Machado022
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: snake-bot
          author_email: actions@github.com
          message: "Atualiza cobrinha 🐍"
          add: "dist/*.svg"
